const express = require("express");
const route = express.Router();
const auth = require("./account");
const formType = require("./form_type");
const standard = require("./standard");
const medium = require("./medium");
const branch = require("./branch");
const gender = require("./gender");
const reference = require("./reference");
const state = require("./state");
const subjectFee = require("./subject_fee");
const grplist = require("./class_grplist");
const country = require("./country");
const district = require("./district");
const admission = require("./admission");
const examFee = require("./exam_fee");
const dashboard = require("./dashboard");
const enquire = require("./enquire");
const subjectFeePayment = require("./subjectFeePayment");

route.use("/auth", auth);
route.use("/formtype", formType);
route.use("/std", standard);
route.use("/medium", medium);
route.use("/branch", branch);
route.use("/gender", gender);
route.use("/reference", reference);
route.use("/state", state);
route.use("/subjectFee", subjectFee);
route.use("/grplist", grplist);
route.use("/country", country);
route.use("/district", district);
route.use("/admission", admission);
route.use("/examFee", examFee); 
route.use("/dashboard", dashboard);
route.use("/enquire", enquire);
route.use("/subjectFeePayment", subjectFeePayment);

module.exports = route;
